import type { SidebarItem } from "@/components/docs-layout";

export const channelkuSidebar: SidebarItem[] = [
  { label: "Dashboard", to: "/docs/channelku/dashboard" },
  { label: "Beralih ke Channelku v2", to: "/docs/channelku/switch-v2" },
  { label: "Reservasi",
  children: [
    { label: "Daftar Reservasi", to: "/docs/channelku/booking-list", },
    { label: "Tambah Reservasi", to: "/docs/channelku/create-reservation", }, ], },
  { label: "Pengaturan", 
    children: [
      { label: "Properti", to: "/docs/channelku/property", },
      { label: "Kamar", to: "/docs/channelku/rooms", },
      { label: "Kebijakan Reservasi", to: "/docs/channelku/booking-policy", } ], },
  { label: "Channel Manager", 
    children: [
      { label: "Penawaran Bulanan", to: "/docs/channelku/monthly-deals", },
      { label: "Penawaran Tahunan", to: "/docs/channelku/yearly-deals", },
      { label: "Panel Kontrol", 
        children: [
          { label: "Panel Kontrol", to: "/docs/channelku/control-panel", },
          { label: "Pemetaan OTA dan IBE", to: "/docs/channelku/mapping-ota-ibe", },
          { label: "Pemetaan PMS", to: "/docs/channelku/mapping-pms", },
          { label: "Saluran OTA",
            children: [
              { label: "Booking.com", to: "/docs/channelku/booking-com", },
              { label: "Agoda", to: "/docs/channelku/agoda", },
              { label: "Airbnb", to: "/docs/channelku/airbnb", },
              { label: "Ctrip", to: "/docs/channelku/ctrip", },
              { label: "Expedia", to: "/docs/channelku/expedia", },
              { label: "Tiket.com", to: "/docs/channelku/tiket-com", },
              { label: "Traveloka", to: "/docs/channelku/traveloka", },
              { label: "Google Hotel", to: "/docs/channelku/google-hotel", },
              { label: "Marriot Homes (HVMB)", to: "/docs/channelku/marriot-homes", },
              { label: "Ikyu", to: "/docs/channelku/ikyu", },
              { label: "Rakuten", to: "/docs/channelku/rakuten", },
              { label: "Hostelworld", to: "/docs/channelku/hostelworld", },
              { label: "Dida Travel", to: "/docs/channelku/dida-travel", },
              { label: "TBO Holidays", to: "/docs/channelku/tbo-holidays", },
              { label: "Bookingina", to: "/docs/channelku/bookingina", },
              { label: "Azana Voyage", to: "/docs/channelku/azana-voyage", },
              { label: "DOTW", to: "/docs/channelku/dotw", },
              { label: "Goibibo", to: "/docs/channelku/goibibo", },
              { label: "Hotelbeds", to: "/docs/channelku/hotelbeds", },
              { label: "Hoterip", to: "/docs/channelku/hoterip", },
              { label: "Mister Aladin", to: "/docs/channelku/mister-aladin", },
              { label: "VillaFinder", to: "/docs/channelku/villafinder", },
              { label: "MG Bedbank", to: "/docs/channelku/mg-bedbank", },
              { label: "Kliknbook", to: "/docs/channelku/kliknbook", }, ], },
          { label: "PMS Channels",
            children: [
              { label: "VHP", to: "/docs/channelku/vhp", },
              { label: "Airhost", to: "/docs/channelku/airhost", },
              { label: "GuestPro", to: "/docs/channelku/guestpro", },
              { label: "Twospaces New", to: "/docs/channelku/twospaces", },
              { label: "Pactindo", to: "/docs/channelku/pactindo", },
              { label: "Hotelmu", to: "/docs/channelku/hotelmu", },
              { label: "Gustodian", to: "/docs/channelku/gustodian", },
              { label: "Powerpro", to: "/docs/channelku/powerpro", },
              { label: "Skyhotel", to: "/docs/channelku/skyhotel", },
              { label: "Pelican", to: "/docs/channelku/pelican", }, ], },
          { label: "Booking Engine Channels", 
            children: [
              { label: "Triplabook", to: "/docs/channelku/triplabook", },
              { label: "Omni Hotelier", to: "/docs/channelku/omni-hotelier", },
              { label: "GuestPro-IBE", to: "/docs/channelku/guestpro-ibe", },
              { label: "Roiback", to: "/docs/channelku/roiback", },
              { label: "Alaric", to: "/docs/channelku/alaric", },
              { label: "BooknPay", to: "/docs/channelku/booknpay", }, ], },
          { label: "RMS Channel", 
            children: [
              { label: "Pricelabs", }, ], }, ], },
      { label: "Saluran Terhubung", to: "/docs/channelku/connected-channel", },
      { label: "Rate Multiplier", to: "/docs/channelku/rate-multiplier", },
      { label: "Alokasi Kamar", to: "/docs/channelku/room-alocation", },
      { label: "iCalendar", to: "/docs/channelku/icalendar", },
      { label: "Sinkronisasi Penuh Otomatis", to: "/docs/channelku/full-synchro-auto", },
      { label: "Pemetaan Internal", to: "/docs/channelku/internal-mapping", },
      { label: "Permintaan Koneksi", to: "/docs/channelku/connect-request", },
      { label: "Laporan", to: "/docs/channelku/report", },
      { label: "Log", to: "/docs/channelku/logs", }, ], },
  { label: "PMS Log",
    children: [
      { label: "Reservasi", to: "/docs/channelku/reservations", }, ], },
  { label: "Back Office System",
    children: [
      { label: "Jurnal", to: "/docs/channelku/journal", }, ], },
  { label: "Akun",
    children: [
      { label: "Penagihan", to: "/docs/channelku/billing", },
      { label: "Detail", to: "/docs/channelku/details", },
      { label: "Sub Users", to: "/docs/channelku/subusers", }, ], },
  { label: "Guest CRM",
    children: [
      { label: "Otomatisasi Email", to: "/docs/channelku/email-autoation", },
      { label: "Guest Database", to: "/docs/channelku/guest-database", }, ], },
  { label: "OTA Content",
    children: [
      { label: "Ulasan Booking.com", to: "/docs/channelku/bookingcom-review", },
      { label: "Promosi OTA", to: "/docs/channelku/promotions-ota", }, ], },
  { label: "Booking.com Set Up", to: "/docs/channelku/bookingcom-setup" },
  { label: "Add-Ons", 
    children: [
      { label: "Dynamic Pricing", to: "/docs/channelku/dynamic-pricing", },
      { label: "Dynamic Minimum Night", to: "/docs/channelku/dynamic-min-night", }, ],}
]; 

export const hotelkuSidebar: SidebarItem[] = [
  { label: "Dashboard", to: "/docs/hotelku/dashboard" },
  { label: "Booking Chart", to: "/docs/hotelku/booking-chart" },
  { label: "Pengaturan Agen", to: "/docs/hotelku/agent-setting" },
  { label: "Akun dan Extras", to: "/docs/hotelku/account-and-extras" },
  { label: "Housekeeping", to: "/docs/hotelku/housekeeping" },
  { label: "Stock Inventory", to: "/docs/hotelku/stock-inventory" },
  { label: "Extras Only", to: "/docs/hotelku/extras-only" },
  { label: "Laporan", to: "/docs/hotelku/reports" },
  { label: "Log", to: "/docs/hotelku/logs" },
  { label: "Pengaturan", to: "/docs/hotelku/settings" },
  { label: "Accounting Apps", to: "/docs/hotelku/accounting-apps" },
];
