/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsChannelkuAccountRouteImport } from './routes/docs.channelku.account'
import { Route as DocsChannelkuBackOfficeRouteImport } from './routes/docs.channelku.back-office'
import { Route as DocsChannelkuChannelManagerRouteImport } from './routes/docs.channelku.channel-manager'
import { Route as DocsChannelkuDashboardRouteImport } from './routes/docs.channelku.dashboard'
import { Route as DocsChannelkuGuestCrmRouteImport } from './routes/docs.channelku.guest-crm'
import { Route as DocsChannelkuOtaContentRouteImport } from './routes/docs.channelku.ota-content'
import { Route as DocsChannelkuPmsLogsRouteImport } from './routes/docs.channelku.pms-logs'
import { Route as DocsChannelkuReservationsRouteImport } from './routes/docs.channelku.reservations'
import { Route as DocsChannelkuSettingsRouteImport } from './routes/docs.channelku.settings'
import { Route as DocsChannelkuSwitchV2RouteImport } from './routes/docs.channelku.switch-v2'
import { Route as DocsHotelkuAccountAndExtrasRouteImport } from './routes/docs.hotelku.account-and-extras'
import { Route as DocsHotelkuAccountingAppsRouteImport } from './routes/docs.hotelku.accounting-apps'
import { Route as DocsHotelkuAgentSettingRouteImport } from './routes/docs.hotelku.agent-setting'
import { Route as DocsHotelkuBookingChartRouteImport } from './routes/docs.hotelku.booking-chart'
import { Route as DocsHotelkuDashboardRouteImport } from './routes/docs.hotelku.dashboard'
import { Route as DocsHotelkuExtrasOnlyRouteImport } from './routes/docs.hotelku.extras-only'
import { Route as DocsHotelkuHousekeepingRouteImport } from './routes/docs.hotelku.housekeeping'
import { Route as DocsHotelkuLogsRouteImport } from './routes/docs.hotelku.logs'
import { Route as DocsHotelkuReportsRouteImport } from './routes/docs.hotelku.reports'
import { Route as DocsHotelkuSettingsRouteImport } from './routes/docs.hotelku.settings'
import { Route as DocsHotelkuStockInventoryRouteImport } from './routes/docs.hotelku.stock-inventory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChannelkuAccountRoute = DocsChannelkuAccountRouteImport.update({
  id: '/docs/channelku/account',
  path: '/docs/channelku/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChannelkuBackOfficeRoute = DocsChannelkuBackOfficeRouteImport.update({
  id: '/docs/channelku/back-office',
  path: '/docs/channelku/back-office',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChannelkuChannelManagerRoute =
  DocsChannelkuChannelManagerRouteImport.update({
    id: '/docs/channelku/channel-manager',
    path: '/docs/channelku/channel-manager',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsChannelkuDashboardRoute = DocsChannelkuDashboardRouteImport.update({
  id: '/docs/channelku/dashboard',
  path: '/docs/channelku/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChannelkuGuestCrmRoute = DocsChannelkuGuestCrmRouteImport.update({
  id: '/docs/channelku/guest-crm',
  path: '/docs/channelku/guest-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChannelkuOtaContentRoute = DocsChannelkuOtaContentRouteImport.update({
  id: '/docs/channelku/ota-content',
  path: '/docs/channelku/ota-content',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChannelkuPmsLogsRoute = DocsChannelkuPmsLogsRouteImport.update({
  id: '/docs/channelku/pms-logs',
  path: '/docs/channelku/pms-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChannelkuReservationsRoute =
  DocsChannelkuReservationsRouteImport.update({
    id: '/docs/channelku/reservations',
    path: '/docs/channelku/reservations',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsChannelkuSettingsRoute = DocsChannelkuSettingsRouteImport.update({
  id: '/docs/channelku/settings',
  path: '/docs/channelku/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChannelkuSwitchV2Route = DocsChannelkuSwitchV2RouteImport.update({
  id: '/docs/channelku/switch-v2',
  path: '/docs/channelku/switch-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHotelkuAccountAndExtrasRoute =
  DocsHotelkuAccountAndExtrasRouteImport.update({
    id: '/docs/hotelku/account-and-extras',
    path: '/docs/hotelku/account-and-extras',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsHotelkuAccountingAppsRoute =
  DocsHotelkuAccountingAppsRouteImport.update({
    id: '/docs/hotelku/accounting-apps',
    path: '/docs/hotelku/accounting-apps',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsHotelkuAgentSettingRoute = DocsHotelkuAgentSettingRouteImport.update({
  id: '/docs/hotelku/agent-setting',
  path: '/docs/hotelku/agent-setting',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHotelkuBookingChartRoute = DocsHotelkuBookingChartRouteImport.update({
  id: '/docs/hotelku/booking-chart',
  path: '/docs/hotelku/booking-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHotelkuDashboardRoute = DocsHotelkuDashboardRouteImport.update({
  id: '/docs/hotelku/dashboard',
  path: '/docs/hotelku/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHotelkuExtrasOnlyRoute = DocsHotelkuExtrasOnlyRouteImport.update({
  id: '/docs/hotelku/extras-only',
  path: '/docs/hotelku/extras-only',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHotelkuHousekeepingRoute = DocsHotelkuHousekeepingRouteImport.update({
  id: '/docs/hotelku/housekeeping',
  path: '/docs/hotelku/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHotelkuLogsRoute = DocsHotelkuLogsRouteImport.update({
  id: '/docs/hotelku/logs',
  path: '/docs/hotelku/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHotelkuReportsRoute = DocsHotelkuReportsRouteImport.update({
  id: '/docs/hotelku/reports',
  path: '/docs/hotelku/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHotelkuSettingsRoute = DocsHotelkuSettingsRouteImport.update({
  id: '/docs/hotelku/settings',
  path: '/docs/hotelku/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHotelkuStockInventoryRoute =
  DocsHotelkuStockInventoryRouteImport.update({
    id: '/docs/hotelku/stock-inventory',
    path: '/docs/hotelku/stock-inventory',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/channelku/account': typeof DocsChannelkuAccountRoute
  '/docs/channelku/back-office': typeof DocsChannelkuBackOfficeRoute
  '/docs/channelku/channel-manager': typeof DocsChannelkuChannelManagerRoute
  '/docs/channelku/dashboard': typeof DocsChannelkuDashboardRoute
  '/docs/channelku/guest-crm': typeof DocsChannelkuGuestCrmRoute
  '/docs/channelku/ota-content': typeof DocsChannelkuOtaContentRoute
  '/docs/channelku/pms-logs': typeof DocsChannelkuPmsLogsRoute
  '/docs/channelku/reservations': typeof DocsChannelkuReservationsRoute
  '/docs/channelku/settings': typeof DocsChannelkuSettingsRoute
  '/docs/channelku/switch-v2': typeof DocsChannelkuSwitchV2Route
  '/docs/hotelku/account-and-extras': typeof DocsHotelkuAccountAndExtrasRoute
  '/docs/hotelku/accounting-apps': typeof DocsHotelkuAccountingAppsRoute
  '/docs/hotelku/agent-setting': typeof DocsHotelkuAgentSettingRoute
  '/docs/hotelku/booking-chart': typeof DocsHotelkuBookingChartRoute
  '/docs/hotelku/dashboard': typeof DocsHotelkuDashboardRoute
  '/docs/hotelku/extras-only': typeof DocsHotelkuExtrasOnlyRoute
  '/docs/hotelku/housekeeping': typeof DocsHotelkuHousekeepingRoute
  '/docs/hotelku/logs': typeof DocsHotelkuLogsRoute
  '/docs/hotelku/reports': typeof DocsHotelkuReportsRoute
  '/docs/hotelku/settings': typeof DocsHotelkuSettingsRoute
  '/docs/hotelku/stock-inventory': typeof DocsHotelkuStockInventoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/channelku/account': typeof DocsChannelkuAccountRoute
  '/docs/channelku/back-office': typeof DocsChannelkuBackOfficeRoute
  '/docs/channelku/channel-manager': typeof DocsChannelkuChannelManagerRoute
  '/docs/channelku/dashboard': typeof DocsChannelkuDashboardRoute
  '/docs/channelku/guest-crm': typeof DocsChannelkuGuestCrmRoute
  '/docs/channelku/ota-content': typeof DocsChannelkuOtaContentRoute
  '/docs/channelku/pms-logs': typeof DocsChannelkuPmsLogsRoute
  '/docs/channelku/reservations': typeof DocsChannelkuReservationsRoute
  '/docs/channelku/settings': typeof DocsChannelkuSettingsRoute
  '/docs/channelku/switch-v2': typeof DocsChannelkuSwitchV2Route
  '/docs/hotelku/account-and-extras': typeof DocsHotelkuAccountAndExtrasRoute
  '/docs/hotelku/accounting-apps': typeof DocsHotelkuAccountingAppsRoute
  '/docs/hotelku/agent-setting': typeof DocsHotelkuAgentSettingRoute
  '/docs/hotelku/booking-chart': typeof DocsHotelkuBookingChartRoute
  '/docs/hotelku/dashboard': typeof DocsHotelkuDashboardRoute
  '/docs/hotelku/extras-only': typeof DocsHotelkuExtrasOnlyRoute
  '/docs/hotelku/housekeeping': typeof DocsHotelkuHousekeepingRoute
  '/docs/hotelku/logs': typeof DocsHotelkuLogsRoute
  '/docs/hotelku/reports': typeof DocsHotelkuReportsRoute
  '/docs/hotelku/settings': typeof DocsHotelkuSettingsRoute
  '/docs/hotelku/stock-inventory': typeof DocsHotelkuStockInventoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/channelku/account': typeof DocsChannelkuAccountRoute
  '/docs/channelku/back-office': typeof DocsChannelkuBackOfficeRoute
  '/docs/channelku/channel-manager': typeof DocsChannelkuChannelManagerRoute
  '/docs/channelku/dashboard': typeof DocsChannelkuDashboardRoute
  '/docs/channelku/guest-crm': typeof DocsChannelkuGuestCrmRoute
  '/docs/channelku/ota-content': typeof DocsChannelkuOtaContentRoute
  '/docs/channelku/pms-logs': typeof DocsChannelkuPmsLogsRoute
  '/docs/channelku/reservations': typeof DocsChannelkuReservationsRoute
  '/docs/channelku/settings': typeof DocsChannelkuSettingsRoute
  '/docs/channelku/switch-v2': typeof DocsChannelkuSwitchV2Route
  '/docs/hotelku/account-and-extras': typeof DocsHotelkuAccountAndExtrasRoute
  '/docs/hotelku/accounting-apps': typeof DocsHotelkuAccountingAppsRoute
  '/docs/hotelku/agent-setting': typeof DocsHotelkuAgentSettingRoute
  '/docs/hotelku/booking-chart': typeof DocsHotelkuBookingChartRoute
  '/docs/hotelku/dashboard': typeof DocsHotelkuDashboardRoute
  '/docs/hotelku/extras-only': typeof DocsHotelkuExtrasOnlyRoute
  '/docs/hotelku/housekeeping': typeof DocsHotelkuHousekeepingRoute
  '/docs/hotelku/logs': typeof DocsHotelkuLogsRoute
  '/docs/hotelku/reports': typeof DocsHotelkuReportsRoute
  '/docs/hotelku/settings': typeof DocsHotelkuSettingsRoute
  '/docs/hotelku/stock-inventory': typeof DocsHotelkuStockInventoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/channelku/account'
    | '/docs/channelku/back-office'
    | '/docs/channelku/channel-manager'
    | '/docs/channelku/dashboard'
    | '/docs/channelku/guest-crm'
    | '/docs/channelku/ota-content'
    | '/docs/channelku/pms-logs'
    | '/docs/channelku/reservations'
    | '/docs/channelku/settings'
    | '/docs/channelku/switch-v2'
    | '/docs/hotelku/account-and-extras'
    | '/docs/hotelku/accounting-apps'
    | '/docs/hotelku/agent-setting'
    | '/docs/hotelku/booking-chart'
    | '/docs/hotelku/dashboard'
    | '/docs/hotelku/extras-only'
    | '/docs/hotelku/housekeeping'
    | '/docs/hotelku/logs'
    | '/docs/hotelku/reports'
    | '/docs/hotelku/settings'
    | '/docs/hotelku/stock-inventory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/channelku/account'
    | '/docs/channelku/back-office'
    | '/docs/channelku/channel-manager'
    | '/docs/channelku/dashboard'
    | '/docs/channelku/guest-crm'
    | '/docs/channelku/ota-content'
    | '/docs/channelku/pms-logs'
    | '/docs/channelku/reservations'
    | '/docs/channelku/settings'
    | '/docs/channelku/switch-v2'
    | '/docs/hotelku/account-and-extras'
    | '/docs/hotelku/accounting-apps'
    | '/docs/hotelku/agent-setting'
    | '/docs/hotelku/booking-chart'
    | '/docs/hotelku/dashboard'
    | '/docs/hotelku/extras-only'
    | '/docs/hotelku/housekeeping'
    | '/docs/hotelku/logs'
    | '/docs/hotelku/reports'
    | '/docs/hotelku/settings'
    | '/docs/hotelku/stock-inventory'
  id:
    | '__root__'
    | '/'
    | '/docs/channelku/account'
    | '/docs/channelku/back-office'
    | '/docs/channelku/channel-manager'
    | '/docs/channelku/dashboard'
    | '/docs/channelku/guest-crm'
    | '/docs/channelku/ota-content'
    | '/docs/channelku/pms-logs'
    | '/docs/channelku/reservations'
    | '/docs/channelku/settings'
    | '/docs/channelku/switch-v2'
    | '/docs/hotelku/account-and-extras'
    | '/docs/hotelku/accounting-apps'
    | '/docs/hotelku/agent-setting'
    | '/docs/hotelku/booking-chart'
    | '/docs/hotelku/dashboard'
    | '/docs/hotelku/extras-only'
    | '/docs/hotelku/housekeeping'
    | '/docs/hotelku/logs'
    | '/docs/hotelku/reports'
    | '/docs/hotelku/settings'
    | '/docs/hotelku/stock-inventory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsChannelkuAccountRoute: typeof DocsChannelkuAccountRoute
  DocsChannelkuBackOfficeRoute: typeof DocsChannelkuBackOfficeRoute
  DocsChannelkuChannelManagerRoute: typeof DocsChannelkuChannelManagerRoute
  DocsChannelkuDashboardRoute: typeof DocsChannelkuDashboardRoute
  DocsChannelkuGuestCrmRoute: typeof DocsChannelkuGuestCrmRoute
  DocsChannelkuOtaContentRoute: typeof DocsChannelkuOtaContentRoute
  DocsChannelkuPmsLogsRoute: typeof DocsChannelkuPmsLogsRoute
  DocsChannelkuReservationsRoute: typeof DocsChannelkuReservationsRoute
  DocsChannelkuSettingsRoute: typeof DocsChannelkuSettingsRoute
  DocsChannelkuSwitchV2Route: typeof DocsChannelkuSwitchV2Route
  DocsHotelkuAccountAndExtrasRoute: typeof DocsHotelkuAccountAndExtrasRoute
  DocsHotelkuAccountingAppsRoute: typeof DocsHotelkuAccountingAppsRoute
  DocsHotelkuAgentSettingRoute: typeof DocsHotelkuAgentSettingRoute
  DocsHotelkuBookingChartRoute: typeof DocsHotelkuBookingChartRoute
  DocsHotelkuDashboardRoute: typeof DocsHotelkuDashboardRoute
  DocsHotelkuExtrasOnlyRoute: typeof DocsHotelkuExtrasOnlyRoute
  DocsHotelkuHousekeepingRoute: typeof DocsHotelkuHousekeepingRoute
  DocsHotelkuLogsRoute: typeof DocsHotelkuLogsRoute
  DocsHotelkuReportsRoute: typeof DocsHotelkuReportsRoute
  DocsHotelkuSettingsRoute: typeof DocsHotelkuSettingsRoute
  DocsHotelkuStockInventoryRoute: typeof DocsHotelkuStockInventoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/channelku/account': {
      id: '/docs/channelku/account'
      path: '/docs/channelku/account'
      fullPath: '/docs/channelku/account'
      preLoaderRoute: typeof DocsChannelkuAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/channelku/back-office': {
      id: '/docs/channelku/back-office'
      path: '/docs/channelku/back-office'
      fullPath: '/docs/channelku/back-office'
      preLoaderRoute: typeof DocsChannelkuBackOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/channelku/channel-manager': {
      id: '/docs/channelku/channel-manager'
      path: '/docs/channelku/channel-manager'
      fullPath: '/docs/channelku/channel-manager'
      preLoaderRoute: typeof DocsChannelkuChannelManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/channelku/dashboard': {
      id: '/docs/channelku/dashboard'
      path: '/docs/channelku/dashboard'
      fullPath: '/docs/channelku/dashboard'
      preLoaderRoute: typeof DocsChannelkuDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/channelku/guest-crm': {
      id: '/docs/channelku/guest-crm'
      path: '/docs/channelku/guest-crm'
      fullPath: '/docs/channelku/guest-crm'
      preLoaderRoute: typeof DocsChannelkuGuestCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/channelku/ota-content': {
      id: '/docs/channelku/ota-content'
      path: '/docs/channelku/ota-content'
      fullPath: '/docs/channelku/ota-content'
      preLoaderRoute: typeof DocsChannelkuOtaContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/channelku/pms-logs': {
      id: '/docs/channelku/pms-logs'
      path: '/docs/channelku/pms-logs'
      fullPath: '/docs/channelku/pms-logs'
      preLoaderRoute: typeof DocsChannelkuPmsLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/channelku/reservations': {
      id: '/docs/channelku/reservations'
      path: '/docs/channelku/reservations'
      fullPath: '/docs/channelku/reservations'
      preLoaderRoute: typeof DocsChannelkuReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/channelku/settings': {
      id: '/docs/channelku/settings'
      path: '/docs/channelku/settings'
      fullPath: '/docs/channelku/settings'
      preLoaderRoute: typeof DocsChannelkuSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/channelku/switch-v2': {
      id: '/docs/channelku/switch-v2'
      path: '/docs/channelku/switch-v2'
      fullPath: '/docs/channelku/switch-v2'
      preLoaderRoute: typeof DocsChannelkuSwitchV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/account-and-extras': {
      id: '/docs/hotelku/account-and-extras'
      path: '/docs/hotelku/account-and-extras'
      fullPath: '/docs/hotelku/account-and-extras'
      preLoaderRoute: typeof DocsHotelkuAccountAndExtrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/accounting-apps': {
      id: '/docs/hotelku/accounting-apps'
      path: '/docs/hotelku/accounting-apps'
      fullPath: '/docs/hotelku/accounting-apps'
      preLoaderRoute: typeof DocsHotelkuAccountingAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/agent-setting': {
      id: '/docs/hotelku/agent-setting'
      path: '/docs/hotelku/agent-setting'
      fullPath: '/docs/hotelku/agent-setting'
      preLoaderRoute: typeof DocsHotelkuAgentSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/booking-chart': {
      id: '/docs/hotelku/booking-chart'
      path: '/docs/hotelku/booking-chart'
      fullPath: '/docs/hotelku/booking-chart'
      preLoaderRoute: typeof DocsHotelkuBookingChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/dashboard': {
      id: '/docs/hotelku/dashboard'
      path: '/docs/hotelku/dashboard'
      fullPath: '/docs/hotelku/dashboard'
      preLoaderRoute: typeof DocsHotelkuDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/extras-only': {
      id: '/docs/hotelku/extras-only'
      path: '/docs/hotelku/extras-only'
      fullPath: '/docs/hotelku/extras-only'
      preLoaderRoute: typeof DocsHotelkuExtrasOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/housekeeping': {
      id: '/docs/hotelku/housekeeping'
      path: '/docs/hotelku/housekeeping'
      fullPath: '/docs/hotelku/housekeeping'
      preLoaderRoute: typeof DocsHotelkuHousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/logs': {
      id: '/docs/hotelku/logs'
      path: '/docs/hotelku/logs'
      fullPath: '/docs/hotelku/logs'
      preLoaderRoute: typeof DocsHotelkuLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/reports': {
      id: '/docs/hotelku/reports'
      path: '/docs/hotelku/reports'
      fullPath: '/docs/hotelku/reports'
      preLoaderRoute: typeof DocsHotelkuReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/settings': {
      id: '/docs/hotelku/settings'
      path: '/docs/hotelku/settings'
      fullPath: '/docs/hotelku/settings'
      preLoaderRoute: typeof DocsHotelkuSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hotelku/stock-inventory': {
      id: '/docs/hotelku/stock-inventory'
      path: '/docs/hotelku/stock-inventory'
      fullPath: '/docs/hotelku/stock-inventory'
      preLoaderRoute: typeof DocsHotelkuStockInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsChannelkuAccountRoute: DocsChannelkuAccountRoute,
  DocsChannelkuBackOfficeRoute: DocsChannelkuBackOfficeRoute,
  DocsChannelkuChannelManagerRoute: DocsChannelkuChannelManagerRoute,
  DocsChannelkuDashboardRoute: DocsChannelkuDashboardRoute,
  DocsChannelkuGuestCrmRoute: DocsChannelkuGuestCrmRoute,
  DocsChannelkuOtaContentRoute: DocsChannelkuOtaContentRoute,
  DocsChannelkuPmsLogsRoute: DocsChannelkuPmsLogsRoute,
  DocsChannelkuReservationsRoute: DocsChannelkuReservationsRoute,
  DocsChannelkuSettingsRoute: DocsChannelkuSettingsRoute,
  DocsChannelkuSwitchV2Route: DocsChannelkuSwitchV2Route,
  DocsHotelkuAccountAndExtrasRoute: DocsHotelkuAccountAndExtrasRoute,
  DocsHotelkuAccountingAppsRoute: DocsHotelkuAccountingAppsRoute,
  DocsHotelkuAgentSettingRoute: DocsHotelkuAgentSettingRoute,
  DocsHotelkuBookingChartRoute: DocsHotelkuBookingChartRoute,
  DocsHotelkuDashboardRoute: DocsHotelkuDashboardRoute,
  DocsHotelkuExtrasOnlyRoute: DocsHotelkuExtrasOnlyRoute,
  DocsHotelkuHousekeepingRoute: DocsHotelkuHousekeepingRoute,
  DocsHotelkuLogsRoute: DocsHotelkuLogsRoute,
  DocsHotelkuReportsRoute: DocsHotelkuReportsRoute,
  DocsHotelkuSettingsRoute: DocsHotelkuSettingsRoute,
  DocsHotelkuStockInventoryRoute: DocsHotelkuStockInventoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
